### ISSUE TITLE
为weasel启用vim模式自动切换中/英输入

### ISSUE THREAD

**Issue by NavyD** [NavyD/rime-wubi86-jidian#1]
在使用nvim中在n/i切换时需要手动切换，导致在从i切换到n模式时如果未主动切换，可能导致输入无效的中文字符

参考[Weasel-定制化 应用设置](https://github.com/rime/weasel/wiki/Weasel-%E5%AE%9A%E5%88%B6%E5%8C%96#%E5%BA%94%E7%94%A8%E8%AE%BE%E7%BD%AE)自动切换

```yaml
# weasel.yaml
app_options:
  cmd.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true
  firefox.exe:
    inline_preedit: true
  gvim.exe:
    ascii_mode: true
    vim_mode: true
```

注意：在vim模式中如果在候选面板中键入`<C-[>`会导致清屏且切换为英文输入法，可能会造成麻烦

参考：

* [feat: vim_mode in app_options #1047](https://github.com/rime/weasel/pull/1047)
